# 1-D Array

In [6]:
import numpy as np
x = [1,2,3,4]
y = np.array(x)
print(y.ndim)

1


# 2-D Array

In [9]:
import numpy as np
x = ([1,2,3,4],[1,2,3,4])
y = np.array(x)
print(y)
print(y.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


# 3-D Array

In [10]:
import numpy as np
x = ([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
y = np.array(x)
print(y)
print(y.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


# Multidimentional Array

In [15]:
import numpy as np
x = np.array([1, 2, 3, 4], ndmin=10) 
print(x)
print(x.ndim) 


[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
