# Create a matrix

In [24]:
import numpy as np

In [25]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)

[[1 2 3]
 [4 5 6]]


# Matrix Addition

In [26]:
var1 = np.matrix([[1,2,3],[4,5,6]])
var2 = np.matrix([[1,2,3],[4,5,6]])
print(var1+var2)

[[ 2  4  6]
 [ 8 10 12]]


# Matrix Substraction

In [27]:
var1 = np.matrix([[1,2,3],[4,5,6]])
var2 = np.matrix([[1,2,3],[4,5,6]])
print(var1-var2)

[[0 0 0]
 [0 0 0]]


# Matrix Multiplication

In [30]:
var1 = np.matrix([[1,2],[4,5]])
var2 = np.matrix([[1,2],[4,5]])
print(var1*var2)
print()
print(var1.dot(var2))

[[ 9 12]
 [24 33]]

[[ 9 12]
 [24 33]]
