In [7]:
import numpy as np

# Addition

In [8]:
var = np.array([1,2,3,4])

varadd = var+3

print(varadd)

[4 5 6 7]


In [16]:
var = np.array([1,2,3,4])

varadd = np.add(var,3)

print(varadd)

[4 5 6 7]


In [10]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1+var2

print(varadd)

[2 4 6 8]


In [15]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1,var2)

print(varadd)

[2 4 6 8]


# Subtraction

In [11]:
var = np.array([1,2,3,4])

varadd = var-3

print(varadd)

[-2 -1  0  1]


# Multiplication

In [12]:
var = np.array([1,2,3,4])

varadd = var*3

print(varadd)

[ 3  6  9 12]


# Division

In [13]:
var = np.array([1,2,3,4])

varadd = var/3

print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


# Modulas

In [14]:
var = np.array([1,2,3,4])

varadd = var%3

print(varadd)

[1 2 0 1]


# Reciprocal

In [17]:
var = np.array([1,2,3,4])

varadd = np.reciprocal(var)

print(varadd)

[1 0 0 0]


In [18]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

varadd2 = var21+var22

print(varadd2)

[[2 4 6 8]
 [2 4 6 8]]
