In [21]:
import numpy as np

In [22]:
var = np.array([1,2,3,4,5,6,7,8])

print("Min : ",np.min(var), np.argmin(var))
print("Max : ",np.max(var), np.argmax(var))
print("Sqrt : ",np.sqrt(var))

Min :  1 0
Max :  8 7
Sqrt :  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712]


In [27]:
var1 = np.array([[2,1,3], [9,5,6]])

print(np.min(var1, axis=0))

[2 1 3]


In [29]:
var = np.array([1,2,3])

print(np.sin(var))
print(np.cos(var))
print(np.cumsum(var))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]
