# Rand()

In [2]:
import numpy as np

var = np.random.rand(4)
var1 = np.random.rand(2,2)

print(var)
print(var1)

[0.73805618 0.83352054 0.55070823 0.40163565]
[[0.86430033 0.54298583]
 [0.12145562 0.99191925]]


# Randn

In [4]:
import numpy as np

var = np.random.randn(2)

print(var)

[1.01582553 0.61651775]


# Ranf

In [5]:
import numpy as np

var = np.random.ranf(2)

print(var)

[0.67494727 0.86509746]


# Randint()

In [8]:
import numpy as np

var = np.random.randint(5,20,5)

print(var)

[ 9  7  6 18 12]
