# Brodcasting

In [1]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])

print(var1+var2)    #error Occurs

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [3]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

print(var1+var2)  #No error

[2 4 6 8]


In [5]:
var1 = np.array([[1],[2]])
var2 = np.array([1,2,3,4])

print(var1.shape)
print()
print(var2.shape)
print()
print(var1+var2)

(2, 1)

(4,)

[[2 3 4 5]
 [3 4 5 6]]
