# Data Types

In [2]:
import numpy as np

var = np.array([1,2,3,4])

print("Data Type:", var.dtype)

Data Type: int32


In [3]:
var = np.array([1.0,2.0,3.1,4.6])

print("Data Type:", var.dtype)

Data Type: float64


In [4]:
var = np.array(["A","S","R"])

print("Data Type:", var.dtype)

Data Type: <U1


In [5]:
var = np.array(["A","S","R",1,2,3])

print("Data Type:", var.dtype)

Data Type: <U11


# Data type convertion

In [6]:
import numpy as np

var = np.array([1,2,3,4],dtype=np.int8)

print("Data Type:", var.dtype)

Data Type: int8


In [8]:
import numpy as np

var = np.array([1,2,3,4], dtype="f")

print("Data Type:", var.dtype)
print(var)

Data Type: float32
[1. 2. 3. 4.]


In [10]:
var = np.array([1,2,3,4])
var_1 = np.float32(var)

print("Data Type:", var.dtype)
print("Data Type:", var_1.dtype)
print(var)
print(var_1)

Data Type: int32
Data Type: float32
[1 2 3 4]
[1. 2. 3. 4.]


In [13]:
var = np.array([1,2,3,4])
var_1 = var.astype(float)

print(var)
print(var_1)

[1 2 3 4]
[1. 2. 3. 4.]
