# Indexing

In [6]:
import numpy as np

In [8]:
var = np.array([1,2,3,4])

print(var[1])
print(var[-3])

2
2


In [9]:
var1 = np.array([[1,2,3,4],[5,6,7,8]])

print(var1[0,1])

2


In [10]:
var2 = np.array([[[1,2],[6,7]]])

print(var2[0,1,0])

6


# Slicing

In [11]:
import numpy as np

In [21]:
var = np.array([9,8,7,6,5,4,3])    #Just see on the index number

print(var)
print()
print("9 to 5 :",var[1:5])
print()
print("9 to End :",var[1:])
print()
print("Start to 5 :",var[:5])
print()
print("Stop :",var[::2])
print()
print("Stop :",var[1:5:2])

[9 8 7 6 5 4 3]

9 to 5 : [8 7 6 5]

9 to End : [8 7 6 5 4 3]

Start to 5 : [9 8 7 6 5]

Stop : [9 7 5 3]

Stop : [8 6]


In [25]:
var1 = np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12]])

print(var1)
print()
print("5 to 11 :",var1[1,1:])

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]

5 to 11 : [ 5  6 11]
