# Insert Function

In [1]:
import numpy as np

In [3]:
var = np.array([1,2,3,4,5])
v = np.insert(var,2,6)
print(var)
print(v)

[1 2 3 4 5]
[1 2 6 3 4 5]


In [4]:
var = np.array([1,2,3,4,5])
v = np.insert(var,(1,3),6)
print(var)
print(v)

[1 2 3 4 5]
[1 6 2 3 6 4 5]


In [8]:
var = np.array([[1,2,3],[4,5,6]])
v1 = np.insert(var,2,6,axis=0)
v2 = np.insert(var,2,6,axis=1)
print(v1)
print()
print(v2)

[[1 2 3]
 [4 5 6]
 [6 6 6]]

[[1 2 6 3]
 [4 5 6 6]]


In [13]:
var = np.array([[1,2,3],[4,5,6]])
v1 = np.insert(var,2,[7,8,9],axis=0)
v2 = np.insert(var,2,[7,8],axis=1)
print(v1)
print()
print(v2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 7 3]
 [4 5 8 6]]


In [15]:
var = np.array([1,2,3,4,5])
v = np.append(var,6)   #Using append function
print(var)
print(v)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [19]:
var = np.array([[1,2,3],[4,5,6]])
v1 = np.append(var,[[7,8,9]],axis=0)   #Using append function
print(var)
print()
print(v1)

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Delete Function

In [20]:
import numpy as np

In [23]:
var1 = np.array([1,2,3,4,5])
d = np.delete(var1,2)
print(var1)
print(d)

[1 2 3 4 5]
[1 2 4 5]
