# Ineration for 1D array

In [1]:
import numpy as np

In [2]:
var = np.array([1,2,3,4,5,6])
print(var)
print()
for i in var :
    print(i)

[1 2 3 4 5 6]

1
2
3
4
5
6


# Ineration for 2D array

In [12]:
var1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(var1)
print()

for i in var1:   
    for j in i:  
        print(j)  

[[1 2 3 4]
 [5 6 7 8]]

1
2
3
4
5
6
7
8


# Ineration for 3D array

In [13]:
var2 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]]])
print(var2)
print()

for i in var2:   
    for j in i: 
        for k in j:
            print(k)  

[[[1 2 3 4]
  [5 6 7 8]]]

1
2
3
4
5
6
7
8


# Using nditer() function

In [19]:
var3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]]])
print(var3)
print()

for i in np.nditer(var3):  
    print(i)

[[[1 2 3 4]
  [5 6 7 8]]]

1
2
3
4
5
6
7
8


In [17]:
var3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]]])
print(var3)
print()

for i in np.nditer(var3,flags=['buffered'],op_dtypes=['S']):  
    print(i)

[[[1 2 3 4]
  [5 6 7 8]]]

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


# Using ndenumerate() function

In [18]:
var3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]]])
print(var3)
print()

for i,d in np.ndenumerate(var3):  
    print(i,d)

[[[1 2 3 4]
  [5 6 7 8]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
