# Join Array

In [1]:
import numpy as np

In [9]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
ar = np.concatenate((var1,var2))
print(ar)

[1 2 3 4 5 6 7 8]


In [4]:
var1 = np.array([[1,2],[3,4]])
var2 = np.array([[5,6],[7,8]])
ar = np.concatenate((var1,var2),axis=1)
print(ar)

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
ar = np.hstack((var1,var2)) #Along with row
print(ar)

[1 2 3 4 5 6 7 8]


In [6]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
ar = np.vstack((var1,var2)) #Along with column
print(ar)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
ar = np.dstack((var1,var2)) #Along with height
print(ar)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# Split Array

In [10]:
import numpy as np

In [14]:
var = np.array([1,2,3,4,5,6])
ar = np.array_split(var,3)
print(var)
print(ar)
print(ar[1])

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[3 4]


In [24]:
var1 = np.array([[1,2],[3,4],[5,6]])
ar = np.array_split(var,3)
ar1 = np.array_split(var,3,axis=1)
print(var1)
print(ar)
print(ar1)

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
