# Transpose Matrix

In [5]:
import numpy as np
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


# Swapaxes Matrix

In [8]:
import numpy as np
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


# Inverse Matrix

In [11]:
import numpy as np
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.inv(var))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


# Power Matrix

In [14]:
import numpy as np
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.matrix_power(var,0))
print()
print(np.linalg.matrix_power(var,2))
print()
print(np.linalg.matrix_power(var,-2))

[[1 2]
 [3 4]]

[[1 0]
 [0 1]]

[[ 7 10]
 [15 22]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


# Determinant Matrix

In [17]:
import numpy as np
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.det(var))

[[1 2]
 [3 4]]

-2.0000000000000004


In [22]:
var1 = np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(var1)
print()
print(np.linalg.det(var1)) 


[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
