# Search Function

In [1]:
import numpy as np

In [2]:
var = np.array([1,2,4,5,6,3,9,8,7,1,2,5,4])
x = np.where(var==2)
print(x)

(array([ 1, 10], dtype=int64),)


In [5]:
var = np.array([4,2,4,5,6,3,9,8,7,1,2,5,4])
x = np.where((var%2)==0)
print(x)

(array([ 0,  1,  2,  4,  7, 10, 12], dtype=int64),)


# Search Sorted Function

In [6]:
import numpy as np

In [10]:
var = np.array([1,2,3,4,6,7,8,9])
x = np.searchsorted(var,5,side="right")
print(x)

4


In [11]:
var = np.array([1,2,3,4,6,7,8,9])
x = np.searchsorted(var,[5,6,7],side="right")
print(x)

[4 5 6]


In [12]:
var = np.array([1,2,3,4,8,9])
x = np.searchsorted(var,[5,6,7],side="right")
print(x)

[4 4 4]


# Sorted Function

In [5]:
import numpy as np

In [13]:
var = np.array([1,6,2,45,89,44])
var1 = np.array(["z","p","s","f"])
print (np.sort(var))
print (np.sort(var1))

[ 1  2  6 44 45 89]
['f' 'p' 's' 'z']


In [14]:
var = np.array([[1,6,2],[45,89,44]])
print (np.sort(var))

[[ 1  2  6]
 [44 45 89]]


# Filter Function

In [15]:
import numpy as np

In [20]:
var = np.array(["z","p","s","f"])
tf = [True, True,False,False]
new_a = var[tf]
print (new_a)

['z' 'p']
