# Shape

In [3]:
import numpy as np

var = np.array([[1,2,3,4],[1,2,3,4]]) #3D Array
var1 = np.array([1,2,3,4], ndmin=4) #Multidimentional Array


print (var)
print(var.shape)
print()
print (var1)
print(var1.shape)

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


# Reshape

In [4]:
import numpy as np

var = np.array([1,2,3,4,5,6])
print(var)
print(var.ndim)
print()

x = var.reshape(3,2)
print(x)
print(x.ndim) #Convertion of 1D array to 2D array

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [5]:
import numpy as np

var1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var1)
print(var1.ndim)
print()

x1 = var1.reshape(2,3,2)
print(x1)
print(x1.ndim) #Convertion of 1D array to 3D array

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [6]:
import numpy as np

var2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var2)
print(var2.ndim)
print()

x2 = var2.reshape(2,3,2)
print(x2)
print(x2.ndim)
print()

one = x2.reshape(-1)
print(one)
print(one.ndim)   #Return the array into 1D array

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
