# Shuffle Function

In [21]:
import numpy as np

In [23]:
var = np.array([1,2,3,4,5,6])
np.random.shuffle(var)
print(var)

[5 6 4 1 3 2]


# Unique Function

In [24]:
import numpy as np

In [26]:
var = np.array([1,2,5,3,4,1,5,6,4,8,4])
x = np.unique(var)
print(x)

[1 2 3 4 5 6 8]


In [29]:
var = np.array([1,2,5,3,4,1,5,6,4,8,4])
x = np.unique(var,return_index=True)
x1 = np.unique(var,return_index=True,return_counts=True)
print(x)
print(x1)

(array([1, 2, 3, 4, 5, 6, 8]), array([0, 1, 3, 4, 2, 7, 9], dtype=int64))
(array([1, 2, 3, 4, 5, 6, 8]), array([0, 1, 3, 4, 2, 7, 9], dtype=int64), array([2, 1, 1, 3, 2, 1, 1], dtype=int64))


# Resize Function

In [30]:
import numpy as np

In [32]:
var = np.array([1,2,3,4,5,6])
y = np.resize(var,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [33]:
#Flatten Function

In [34]:
import numpy as np

In [38]:
var = np.array([[1,2,3],[4,5,6]])
print(var.flatten())
print(var.flatten(order="F"))

[1 2 3 4 5 6]
[1 4 2 5 3 6]


# Reval Function

In [41]:
var = np.array([[1,2,3],[4,5,6]])
print(var.ravel())
print(var.ravel(order="F"))

[1 2 3 4 5 6]
[1 4 2 5 3 6]
