# Array filled with zeros

In [3]:
import numpy as np

arr_zero = np.zeros(4)
arr_zero1 = np.zeros((3,4))

print(arr_zero)
print()
print(arr_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Array filled with ones

In [4]:
import numpy as np

arr_one = np.ones(4)
arr_one1 = np.ones((3,4))

print(arr_one)
print()
print(arr_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Create an empty array

In [5]:
import numpy as np

arr_em = np.empty(4)

print(arr_em)

[1. 1. 1. 1.]


# Create an array with a range of elements

In [7]:
import numpy as np

arr_ren = np.arange(4)

print(arr_ren)

[0 1 2 3]


# Create an array diagonal element filled with 1's

In [9]:
import numpy as np

arr_dia = np.eye(2)

print(arr_dia)

[[1. 0.]
 [0. 1.]]


# Create an array with values that are spaced with linearly in a specified interval

In [11]:
import numpy as np

arr_lin = np.linspace(0,20,num=5)

print(arr_lin)

[ 0.  5. 10. 15. 20.]
