# Array

In [1]:
import numpy as np
x = [1,2,3,4]
y = np.array(x)
print(y)

[1 2 3 4]


In [2]:
import numpy as np
x = [1,2,3,4]
y = np.array(x)
y

array([1, 2, 3, 4])

In [4]:
l = []
for i in range (1,5):
    int1 = int(input("Enter:"))
    l.append(int1)
print(np.array(l))

Enter:10
Enter:20
Enter:30
Enter:40
[10 20 30 40]
